---
image: debian:12

stages:
  - build
  - test

before_script:
  - apt-get update
  - apt-get -y dist-upgrade
  - apt-get -y install ca-certificates git golang make

build-job:
  stage: build
  script:
    - make tidy
    - make verify
    - make
    - make release
    - find build ! -type d ! -name SHA256SUMS -exec sha256sum '{}' \; >build/SHA256SUMS
    - cat build/SHA256SUMS
  artifacts:
    paths:
      - ./build
    expire_in: 1 week

test-job:
  stage: test
  script:
    make test
    make check
