name: Pipeline

on: [push, pull_request]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    container:
      image: debian:12
    steps:
      - name: Prepare signing key
        run: |
          echo 'dev-personal-git@iodine ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOaK5/rx1e5OSInMYOwoLeGyIwi7Hpao0qUC4oyO0/Wr' >"${HOME}/.signers"

      - name: Prepare packages
        run: |
          apt-get update
          apt-get -y dist-upgrade
          apt-get -y install ca-certificates git golang make

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: |
          chown -R root:root .
          git -c gpg.ssh.allowedSignersFile="${HOME}/.signers" verify-commit HEAD
          make tidy
          make verify
          make
          make release
          find build ! -type d ! -name SHA256SUMS -exec sha256sum --tag '{}' \; >build/SHA256SUMS
          cat build/SHA256SUMS |sort

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./build
      - name: Test
        run: |
          make check
          make test
